server:
  port: 8900
spring:
  redis:
#    单机部署
    port: 6379
    host:
    lettuce:
      pool:
        #最大连接数
        max-active: 20
        #最小空闲连接数
        min-idle: 5
        #最大空闲连接数
        max-idle: 10
    username:
    password:
#   哨兵模式
#    sentinel:
#      nodes: 192.168.116.108:26379
#      master: mymaster
#    password: 123456
demo:
  redis:
    topic: user,emp